version: '3'
services:
  dev-container:
    # image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
    build:
      context: ./
    working_dir: /workspaces
    container_name: vscode-server.code-snippets
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes: 
      - ${WORKSPACES_DIR}/code-snippets:/workspaces/
      - ./install.sh:/install.sh
